# Generated by Django 4.2.7 on 2023-12-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ccode', models.BigIntegerField()),
            ],
        ),
    ]
